config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  get 'users/new'
  get 'pages/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  post "/direction_create" => "recipes#direction_create"
  resources :directions

  resources :users
  resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction < ApplicationRecord
    belongs_to :recipe

    mount_uploader :image, ImageUploader
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    
    validates :user_id, presence: true
    # validates :name, presence: true
    # validates :main_image, presence: true
    # validates :ingredient, presence: true
    # validates :description, presence: true

    mount_uploader :image, ImageUploader
    mount_uploader :main_image, ImageUploader

    belongs_to :user
    has_many :directions
    has_many :favorites
    has_many :favorite_users, through: :favorites, source: 'user'

end

app/models/report.rb
class Report < ApplicationRecord
    
    validates :recipe_id, presence: true
    validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    # validates :name, presence: true, length: { maximum: 15 }
    # validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    # validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i }

    has_secure_password

    has_many :recipes
    has_many :favorites
    has_many :favorite_recipes, through: :favorites, source: 'recipe'
    has_many :directions
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    add_flash_types :success, :info, :warning, :danger
  
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end
  
    def logged_in?
      !current_user.nil?
    end
  end   

app/controllers/directions_controller.rb
class DirectionsController < ApplicationController
    # def new
    #     @direction = Direction.new
    # end

    # def create
    #     @direction = Direction.new(direction_params)
    #     @direction.recipe_id = current_user.id
    #     if @direction.save
    #     redirect_to topics_path, success: 'コメントを投稿しました'
    #     else
    #     redirect_to topics_path, danger: 'コメントの投稿に失敗しました'
    #     end
    # end

    # private
    # def direction_params
    #     params.require(:direction).permit(:image,:comment,:number,:recipe_id)
    # end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

    def index
    @favorite_recipes = current_user.favorite_recipes
    end

    def create
        favorite = Favorite.new
        favorite.user_id = current_user.id
        favorite.recipe_id = params[:recipe_id]

        if favorite.save
            redirect_to recipes_path, success: 'お気に入りに登録しました'
        else
            redirect_to recipes_path, danger: 'お気に入りに登録に失敗しました'
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

    def  new
        @recipe = Recipe.new
    end

    def  index
        @recipes = Recipe.all.includes(:favorite_users, :directions)
        
    end

    def create

        # direction1 = Direction.new
        # direction1.recipe_id = 44
        # direction1.number = 1
        # direction1.comment = "test"
        # direction1.image = "tes"
        # direction1.save!




        @recipe = current_user.recipes.new(recipe_params)
        if @recipe.save
            unless params["direction1"].empty?
                direction1 = Direction.new
                direction1.recipe_id = @recipe.id
                direction1.number = 1
                direction1.comment = params["direction1"]["comment"]
                direction1.image = params["direction1"]["image"]
                 binding.pry
                if direction1.save
                    direction2 = Direction.new
                    direction2.recipe_id = @recipe.id
                    direction2.number = 1
                    direction2.comment = params["direction1"]["comment"]
                    direction2.image = params["direction1"]["image"]
                if direction2.save
    
                    # redirect_to recipes_path, success: '投稿に成功しました'
                    render :new 
                else
                    flash.now[:danger] = "投稿に失敗しました"
                    render :new 
                    
                end
            end
        end
    end

    def edit
        @recipe = Recipe.find_by(id: params[:id])
        
    end

    def  update
    @recipe = Recipe.find_by(id: params[:id])
        @recipe.update(recipe_params)
        if @recipe.save
        redirect_to recipes_path, success: '投稿に成功しました'
        else
        flash.now[:danger] = "投稿に失敗しました"
        render :new
        end
    end

    def  destroy
        @recipe = Recipe.find_by(id: params[:id])
        @recipe.destroy
        redirect_to recipes_path, success: '投稿を削除しました'
    end
    
    private
    def recipe_params
        params.require(:recipe).permit(:main_image, :description, :name, :ingredient, :situation, :point, :user_id)
    end
    #private
    # def direction1_params
    #     params.require(:direction).permit(:comment, :image)
    # end

end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
  log_out
  redirect_to root_url, info: 'ログアウトしました'
  end

private
  def log_in(user)
  session[:user_id] = user.id
  end

  def log_out
  session.delete(:user_id)
  @current_user = nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:alert] = "登録に失敗しました"
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
      !current_user.nil?
    end
end

app/helpers/directions_helper.rb
module DirectionsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<div class="topic-index-wrapper">
    <div class="container">
            <h1 class="text-center function-name">Favorites</h1>
        <% @favorite_recipes.each do |recipe| %>
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="topic-index-single">
                    <h2 class="topic-author">
                        <%= recipe.user.name %>
                    </h2>
                    <%= image_tag recipe.main_image.url %>
                    <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
                    <p class="topic-text">
                        <%= recipe.description %>
                    </p>
                </div>
            </div>
        </div>
        <% end %>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Recipepad</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>" role="alert">
    <%= value %>
  </div>
  <% end %>

  <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
    <div class="container">
      <%= link_to root_path do %>
      <span>
        <%= image_tag "icons/recipelogo.png", class: "navbar-brand" %></span>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li>
          <%= link_to favorites_index_path do %>
          <%= image_tag 'icons/heart.png' %>
          <% end %>
        </li>
        <li>  
          <%= link_to recipes_path do %>
          <%= image_tag "icons/index.png" %>
          <% end %>
        </li>
        <li>
          <%= link_to new_recipe_path do %>
          <%= image_tag "icons/recipeadd.png" %>
          <% end %>
        </li>
        <li>
          <%= link_to "#" do %>
          <%= image_tag "icons/gochirepo.png" %>
          <% end %>
        </li>
        <li>
          <%= link_to logout_path, method: :delete do %>
          <%= image_tag "icons/logout.png" %>
          <% end %>
        </li>
        <% else %>
        <li>
          <%= link_to new_user_path do %>
          <%= image_tag "icons/register.png" %>
          <% end %>
        </li>
        <li>
          <%= link_to login_path do %>
          <%= image_tag "icons/login.png" %>
          <% end %>
        </li>
        <% end %>
      </ul>
    </div>
  </nav>

  <%= yield %>


  <script>
    $(function () {
      $(".alert").fadeOut(5000);
    });
  </script>

</body>

</html>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
    <div class="container top-hero-container">
        <h1 class="text-white">Make you Happy</h1>
        <h2 class="text-white">Recipepad is a service that you can post recipes.</h2>
        <div class="row">
            <div class="col-md-offset-3 col-md-3">
                <%= link_to 'Sign up', new_user_path, class: 'btn btn-block btn-white' %>
            </div>
            <div class="col-md-3">
                <%= link_to 'Log in', login_path, class: 'btn btn-block btn-white' %>
            </div>
        </div>
    </div>
</div>

app/views/recipes/edit.html.erb
<div class="topic-new-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <h1 class="text-center function-name">Edit Recipe</h1>
                <%= form_for @recipe do |f| %>

                <!-- <%= f.text_area :id, class: 'form-control' %> -->
                <%= f.hidden_field :id %>

                <div class="form-group">
                    <%= f.label :料理名 %>
                    <%= f.text_area :name, class: 'form-control' %>
                </div>

                <div class="form-group">
                    <%= f.label :写真 %>
                    <%= f.file_field :main_image %>
                </div>

                <div class="form-group">
                    <%= f.label :紹介文 %>
                    <%= f.text_area :description, class: 'form-control' %>
                </div>

                <div class="form-group">
                    <%= f.label :材料 %>
                    <%= f.text_area :ingredient, class: 'form-control' %>
                </div>

                <div class="form-group">
                    <%= f.label :作った背景 %>
                    <%= f.text_area :situation, class: 'form-control' %>
                </div>

                <div class="form-group">
                    <%= f.label :コツ・ポイント %>
                    <%= f.text_area :point, class: 'form-control' %>
                </div>

                <%= f.submit '投稿', class: 'btn btn-black btn-block' %>

                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/recipes/index.html.erb
<div class="topic-index-wrapper">
    <div class="container">
        <% @recipes.each do |recipe| %>
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="topic-index-single">
                    <h2 class="topic-author">
                        <%= link_to recipe_path(id: recipe.id), method: :get do %>
                        <%= recipe.name %>
                        <% end %>
                    </h2>
                    <h4 class="topic-author">
                        <%= recipe.description %>
                    </h4>
                    <h3 class="topic-author">
                        <%= recipe.user.name %>
                    </h3>
                    <%= image_tag recipe.main_image.url %>
                    

                    <% if !recipe.favorite_users.include?(current_user) %>
                        <%= link_to favorites_path(recipe_id: recipe.id), method: :post do %>
                        <%= image_tag 'icons/heart-black.png', class: 'topic-index-icon' %>
                        <% end %>
                    <% end %>

                    <%= link_to recipe_path(id: recipe.id), method: :delete do %>
                    <%= image_tag 'icons/delete.png', class: 'topic-index-icon' %>
                    <% end %>

                    <%= link_to edit_recipe_path(id: recipe.id), method: :get do %>
                    <p class="topic-index-icon">編集</p>
                    <% end %>

                    <p class="topic-text">
                        材料：
                        <%= recipe.ingredient %>
                    </p>
                    <p class="topic-text">
                        作った背景：
                        <%= recipe.situation %>
                    </p>
                    <p class="topic-text">
                        コツ・ポイント：
                        <%= recipe.point %>
                    </p>
                </div>

            </div>
        </div>


        <% end %>
    </div>
</div>

app/views/recipes/new.html.erb
<div class="topic-new-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <h1 class="text-center function-name">Add Recipe</h1>

                <%= form_tag("/recipes", method: :post, multipart: true) do %>
                <div class="form-group">
                    <%= label_tag '料理名' %>
                    <%= text_field_tag 'recipe[name]' ,'',class: 'form-control'%>
                </div>

                <div class="form-group">
                    <%= label_tag '写真' %>
                    <%= file_field_tag 'recipe[main_image]' %>
                </div>

                <div class="form-group">
                    <%= label_tag '紹介文' %>
                    <%= text_area_tag 'recipe[description]','',class: 'form-control' %>
                </div>

                <div class="form-group">
                    <%= label_tag '材料' %>
                    <%= text_area_tag 'recipe[ingredient]' ,'',class: 'form-control'%>
                </div>

                <div class="form-group">
                    <%= label_tag '作った背景' %>
                    <%= text_area_tag 'recipe[situation]','',class: 'form-control' %>
                </div>

                <div class="form-group">
                    <%= label_tag 'コツ・ポイント' %>
                    <%= text_area_tag 'recipe[point]' ,'',class: 'form-control'%>
                </div>

                <div class="form-direction">
                    <div>
                        <h2>1</h2>
                        <%= hidden_field_tag :number , :value => 1 %>
                    </div>
                    <div>
                        <%= label_tag '作り方' %>
                        <%= text_area_tag 'direction1[comment]','',class: 'form-control' %>
                    </div>
                    <div>
                        <%= label_tag '写真' %>
                        <%= file_field_tag 'direction[image]' %>
                    </div>

                    <div>
                        <h2>2</h2>
                        <%= hidden_field_tag :number , :value => 2 %>
                    </div>
                    <div>
                        <%= label_tag '作り方' %>
                        <%= text_area_tag 'direction2[comment]','',class: 'form-control' %>
                    </div>
                    <div>
                        <%= label_tag '写真' %>
                        <%= file_field_tag 'direction[image]' %>
                    </div>
                </div>

                <%= submit_tag  '送信', class: 'btn btn-black btn-block' %>
                <% end %>

            </div>
        </div>
    </div>
</div>

app/views/recipes/show.html.erb
<div class="topic-index-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="topic-index-single">
                    <h2 class="topic-author">
                        <%= link_to edit_recipe_path(id: @recipe.id), method: :get do %>
                        <%= @recipe.name %>
                        <% end %>
                    </h2>

                    <%= image_tag @recipe.main_image.url %>
                    <p class="topic-text">
                        材料：
                        <%= @recipe.ingredient %>
                    </p>
                    <p class="topic-text">
                        作った背景：
                        <%= @recipe.situation %>
                    </p>
                    <p class="topic-text">
                        コツ・ポイント：
                        <%= @recipe.point %>
                    </p>

                    <% @recipe.directions.each do |direction| %>
                    <div class="form-direction">
                        <div>
                            <h2>
                                <%= direction.number %>
                            </h2>
                        </div>
                        <div>
                            <%= image_tag direction.image.url %>
                        </div>
                        <div>
                            作り方:
                            <%= direction.comment %>
                        </div>
                    </div>
                    <% end %>
                </div>

                <!-- <%= form_for Direction.new,url: "/direction_create" do |f| %>
                <%= f.file_field :image %>
                <%= f.text_area :comment %>
                <%= f.hidden_field :recipe_id,value: params[:id]%>
                <%  if @recipe.directions.blank? %>
                <%= f.hidden_field :number,value: 1%>
                <% else%>
                <%= f.hidden_field :number,value: @recipe.directions.last.number+1%>
                <% end %>
                <%= submit_tag "作り方を投稿する" %>
                <% end %> -->
            </div>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign up</h1>
        <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.label :name, class: 'text-white' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email, class: 'text-white' %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password, class: 'text-white' %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, class: 'text-white' %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>

        <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path, class: 'text-white' %>
      </div>
    </div>
  </div>
</div>